#!/bin/bash

if id "$1" &>/dev/null;

then

echo "User $1 already exists."

echo "please chose another username."

exit

else

read - p "password" pswd

useradd -p "$pswd" -d /home/"$1" -m-g users -s /bin/bash "$1"

echo "$1 added"

